refresh_now:
  name: Refresh Now
  description: Manually refresh meme stock data
  fields:
    entity_id:
      name: Entity ID
      description: Specific meme stock entity to refresh (optional)
      required: false
      selector:
        entity:
          domain: sensor
          integration: meme_stock_insight

set_weighting:
  name: Set Weighting
  description: Update the weighting factors for impact score calculation
  fields:
    volume_weight:
      name: Volume Weight
      description: Weight for volume score (0.0-1.0)
      required: true
      default: 0.40
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
    sentiment_weight:
      name: Sentiment Weight
      description: Weight for sentiment score (0.0-1.0)
      required: true
      default: 0.30
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
    momentum_weight:
      name: Momentum Weight
      description: Weight for momentum score (0.0-1.0)
      required: true
      default: 0.20
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider
    short_interest_weight:
      name: Short Interest Weight
      description: Weight for short interest score (0.0-1.0)
      required: true
      default: 0.10
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.05
          mode: slider

force_update_cache:
  name: Force Update Cache
  description: Force update the instrument cache from Trading212 and exchanges
  fields: {}

clear_historical_data:
  name: Clear Historical Data
  description: Clear stored historical data for all tickers
  fields:
    confirm:
      name: Confirm
      description: Type 'CONFIRM' to clear all historical data
      required: true
      selector:
        text:
